### PR TITLE
 Indexing and Lucene Search Improvements

### LINKED ISSUE #41: Log page crashes when Elasticsuite is installed
### Issue

With `mage-os/mageos-async-events` installed, navigating to "Stores > Asynchronous Events > Logs" crashes the page with an error.

```
1 exception(s):
Exception #0 (RuntimeException): Search client is not set.

Exception #0 (RuntimeException): Search client is not set.
#1 Magento\Elasticsearch\SearchAdapter\ConnectionManager->getConnection() called at [vendor/mage-os/mageos-async-events/Model/Indexer/LuceneSearch.php:52]
#2 MageOS\AsyncEvents\Model\Indexer\LuceneSearch->prepare() called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:164]
#3 Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(&MageOS\AsyncEvents\Model\Indexer\LuceneSearch#000000000000065c0000000000000000#) called at [vendor/magento/framework/View/Layout/Generator/UiComponent.php:161]
...
```

Investigating this shows that the `elasticsuite` client has not been added to the `\Magento\Elasticsearch\ElasticAdapter\Model\Client\ClientFactoryProxy` for resolution.

Image

The indexer `\MageOS\AsyncEvents\Model\Indexer\AsyncEventSubscriber` also fails because it has a dependency on the `\Magento\Elasticsearch\Model\Adapter\ElasticsearchFactory`, which tries to connect to the client in this configuration scenario.

### Solution Ideas

1. I think it would be good to add `dependsOnConfig="system/async_events/indexing_enabled"` to the root menu node titled "Asynchronous Events" so the links are hidden when indexing is disabled.
2. I have a question into the `Smile-SA/elasticsuite` repo to see about an implementation of `\Magento\AdvancedSearch\Model\Client\ClientInterface` so this module could use the `\Magento\AdvancedSearch\Model\Client\ClientResolver` for a more universal approach. Would there be any opposition to swapping out the implementation used in `LuceneSearch`?

I'd like to try and get these two modules working together, so hoping to get a conversation started on possible solutions.

### Preconditions

Magento `v2.4.7-p2`
Elasticsuite `v2.11.10`
mage-os/mageos-async-events `v4.0.4`

### LINKED ISSUE #44: Incorrect records are indexed
It looks like every single event is indexed across all event types.

Example:

In a given scenario where there are 178 asynchronous event logs, all 178 events (of different types) are present in all of the different dimensions.

This cannot be correct because the sum of these should make 178.

```
GET /_cat/indices/magento2_async_event_*
                             
magento2_async_event_sales.order.created_v5  1 1 178
magento2_async_event_customer.created_v5     1 1 178
magento2_async_event_customer.login_v5       1 1 178
magento2_async_event_cart.product.added_v5   1 1 178
magento2_async_event_customer.updated_v5     1 1 178
```

In the database, grouping the events by `event_name` produces the following, and this is what each namespace in OpenSearch should also have.

```
MariaDB [magento2]> SELECT l.subscription_id, COUNT(l.log_id) AS log_count, e.event_name FROM async_event_subscriber_log AS l JOIN async_event_subscriber AS e ON e.subscription_id = l.subscription_id GROUP BY l.subscription_id, e.event_name;

+-----------------+---------------------+---------------+
| subscription_id | event_name          | count(log_id) |
+-----------------+---------------------+---------------+
|               5 | customer.login      |            44 |
|               6 | customer.created    |            50 |
|               7 | customer.updated    |            19 |
|               8 | cart.product.added  |            28 |
|               9 | sales.order.created |            37 |
+-----------------+---------------------+---------------+
```

### PR DESCRIPTION
**Pull request by gowrizrh**
Fixes #41 
Fixes #44

### CODE REVIEW

**Review by anthonydinino — APPROVED** [review]
LGTM

File: Model/Indexer/LuceneSearch.php [hunk 1]
```diff
@@ -32,6 +34,7 @@ public function __construct(
         FilterModifier $filterModifier,
         private readonly ConnectionManager $connectionManager,
         private readonly Config $config,
```
Comment (avstudnitz) [inline Model/Indexer/LuceneSearch.php]: Can you introduce an alias `ElasticSearchConfig` for the `Config` class and also adjust the variable name to `$elasticsearchConfig` so the distinction between the two config objects are clear?

File: Model/Indexer/LuceneSearch.php [hunk 2]
```diff
@@ -49,38 +52,49 @@ public function __construct(
...
-                    'q' => $value,
-                    // the default page size is 10. The highest limit is 10000. If we want to traverse further, we will
-                    // have to use the search after parameter. There are no plans to implement this right now.
-                    'size' => 100
-                ]
-            );
+        if ($this->asyncEventsConfig->isIndexingEnabled()) {
+            $client = $this->connectionManager->getConnection();
+            $indexPrefix = $this->config->getIndexPrefix();
+            $filter = $this->filterBuilder->setConditionType('in')
```
Comment (avstudnitz) [inline Model/Indexer/LuceneSearch.php:67]: If we want to be exact, we should use `$filterBuilder` instead of `$filter`, but I like the better readability of `$filter`, so we can leave it as is.

File: Model/Indexer/LuceneSearch.php [hunk 3]
```diff
@@ -49,38 +52,49 @@ public function __construct(
...
+                $rawDocuments = $rawResponse['hits']['hits'] ?? [];
+                $asyncEventIds = array_column($rawDocuments, '_id');
 
-            if (!empty($asyncEventIds)) {
-                $filter->setValue($asyncEventIds);
-            } else {
+                if (!empty($asyncEventIds)) {
+                    $filter->setValue($asyncEventIds);
+                } else {
+                    $filter->setValue("0");
```
Comment (avstudnitz) [inline Model/Indexer/LuceneSearch.php]: I always like single quotation marks in PHP. It's not important though.

**Review by avstudnitz — COMMENTED** [review]
I like the changes, they improve the code and make it more clear.
I'd like to have the alias in, everything else is optional.

File: Model/Indexer/LuceneSearch.php (hunk 3 above)
Comment (gowrizrh) [reply Model/Indexer/LuceneSearch.php]: yeah all other quotes in this file uses single quotes, updated to be consistent now.

File: Model/Indexer/LuceneSearch.php (hunk 2 above)
Comment (gowrizrh) [reply Model/Indexer/LuceneSearch.php:67]: leaving it as is

File: Model/Indexer/LuceneSearch.php (hunk 1 above)
Comment (gowrizrh) [reply Model/Indexer/LuceneSearch.php]: this has been updated, the variable has been renamed and class alias introduced

**Review by avstudnitz — APPROVED** [review]
Good changes!
