### PR TITLE
Index large amount of event records

### LINKED ISSUE #35: Fatal error: Allowed memory size exhausted during `indexer:reindex async_event`
When there is a large number of async event logs, the `indexer:reindex async_event` command may fail with the following error:

```
Fatal error: Allowed memory size of X bytes exhausted (tried to allocate Y bytes) in /var/www/html/vendor/magento/framework/DB/Statement/Pdo/Mysql.php
```

I had around 200,000 events to index and a memory limit of 128M for which this process failed.

### LINKED ISSUE #36: Incorrect search index create / delete handling
There is currently an issue where the index create and delete handling is wrong.

When the index is created for the first time
image

After running `indexer:reindex async_event` some 50 times, the indexes are not correctly handled. Instead it loops around in some way. The correct index number should have been `magento2_async_event_sales.order.created_v50` and all old ones deleted

image

### PR DESCRIPTION
**Pull request by gowrizrh**
Fixes #35
Fixes #36

Instead of loading everything in the `async_event_subscriber_log` table, this change uses cursor pagination to load rows from the database in batches.

### CODE REVIEW

File: Model/Indexer/DataProvider/AsyncEventSubscriberLogs.php [hunk 1]
```diff
@@ -4,17 +4,32 @@
...
+use MageOS\AsyncEvents\Model\Indexer\AsyncEventSubscriber;
 use MageOS\AsyncEvents\Model\ResourceModel\AsyncEventLog\Collection;
 use MageOS\AsyncEvents\Model\ResourceModel\AsyncEventLog\CollectionFactory as AsyncEventLogCollectionFactory;
+use Zend_Db_Expr;
 
 class AsyncEventSubscriberLogs
 {
+    private AdapterInterface $connection;
+
+    private const DEPLOYMENT_CONFIG_INDEXER_BATCHES = 'indexer/batch_size/';
```
Comment (sprankhub) [inline Model/Indexer/DataProvider/AsyncEventSubscriberLogs.php]: Minor: Can we add something like `_PREFIX` to clarify that it is not the full config path?

File: Model/Indexer/DataProvider/AsyncEventSubscriberLogs.php [hunk 2]
```diff
@@ -42,4 +57,35 @@ public function getAsyncEventLogs(string $asyncEvent, ?array $logIds): Collectio
...
+
+            if (empty($result)) {
+                break;
+            }
+
+            foreach ($result as $row) {
+                yield $row['log_id'] => $row;
+            }
+
+            $lastId = end($result)["log_id"];
```
Comment (sprankhub) [inline Model/Indexer/DataProvider/AsyncEventSubscriberLogs.php]:
```suggestion
            $lastId = end($result)['log_id'];
```

File: docs/Webhooks.png
Comment (sprankhub) [inline docs/Webhooks.png:1]: Did you delete these images on purpose?

Comment (gowrizrh) [reply docs/Webhooks.png:1]: Yes that's correct. They're outdated and not used in the README :slightly_smiling_face:

File: Model/Indexer/DataProvider/AsyncEventSubscriberLogs.php (hunk 1 above)
Comment (gowrizrh) [reply Model/Indexer/DataProvider/AsyncEventSubscriberLogs.php]: happy to change this, this name / patter (of prefixing) is just taken from core code

image

**Review by sprankhub — APPROVED** [review]
